### ISSUE TITLE
Downloading from S3: Access denied

### ISSUE THREAD

**Issue by skjerns** [Dreem-Organization/dreem-learning-open#1]
Great paper and absolutely amazing initative to publish your results open source.

I'm trying to recreate your results, however I'm unable to download the dataset from S3. 

```Python
ClientError: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied
```
Is the dataset publicly available?

**Comment by vthorey** [comment]
Thanks for the feedback!

Indeed the dataset was not publicly available, it is fixed now!

Do not hesitate to keep us posted with your results  ;)

Valentin

**Comment by skjerns** [comment]
thanks for the quick update!

now I'm getting: 
```
ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

**Comment by vthorey** [comment]
Oh sorry for that It is functional now.

**Comment by Usman-j** [comment]
Thanks a lot for making your work open source. I am trying to download the dataset using the provided script but facing the same issue;
![image](https://user-images.githubusercontent.com/39987619/81629458-bccdc180-9435-11ea-8064-e6938f100aa4.png)

**Comment by vthorey** [comment]
You should now be able to download the data. Thank your for your feedback!

**Comment by Irving-ren** [comment]
Thanks for sharing your work and opening this dataset.  I'm trying to download the dataset but occurring this issue. The error info as follows.

`Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/opt/conda/lib/python3.6/site-packages/urllib3/response.py", line 442, in read
    data = self._fp.read(amt)
  File "/opt/conda/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/opt/conda/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/opt/conda/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/opt/conda/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/conda/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/opt/conda/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download_data.py", line 16, in <module>
    Filename=DODO_SETTINGS["h5_directory"] + "/{}".format(filename)
  File "/opt/conda/lib/python3.6/site-packages/boto3/s3/inject.py", line 172, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/opt/conda/lib/python3.6/site-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/opt/conda/lib/python3.6/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/opt/conda/lib/python3.6/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/opt/conda/lib/python3.6/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/opt/conda/lib/python3.6/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/opt/conda/lib/python3.6/site-packages/s3transfer/download.py", line 521, in _main
    for chunk in chunks:
  File "/opt/conda/lib/python3.6/site-packages/s3transfer/download.py", line 649, in __next__
    chunk = self._body.read(self._chunksize)
  File "/opt/conda/lib/python3.6/site-packages/s3transfer/utils.py", line 551, in read
    value = self._stream.read(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/botocore/response.py", line 77, in read
    chunk = self._raw_stream.read(amt)
  File "/opt/conda/lib/python3.6/site-packages/urllib3/response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/opt/conda/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/conda/lib/python3.6/site-packages/urllib3/response.py", line 378, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
`
